import { rel } from "./constants";

/* ═══════════════════════════════════════════════════════════════════
   STATE — single source of truth
   All UI labels, specialist prompts, alerts, and calculations
   derive from this object. No duplicate facts.
═══════════════════════════════════════════════════════════════════ */
const STATE = {
  owner: { name: "Kunal Mehta", residency: "UAE", entity_count: 6 },
  entities: [
    {
      id: "ss", name: "Six Scents Perfume General Trading L.L.C.", short: "Six Scents",
      type: "operating", jurisdiction: "UAE", currency: "AED", ownership: 100, status: "active", color: "#C9A84C",
      description: "UAE mainland. Perfume wholesale & distribution. Key suppliers: Coty, Puig, Rasasi, Lattafa, Armaf.",
      tax_rate: 9, tax_regime: "UAE CT",
      cash: 380000, debt: 0, receivables: 290000, payables: 145000, monthly_burn: 95000,
      receivables_aging: { d0_30: 120000, d31_60: 95000, d61_90: 48000, d90p: 27000 },
      payables_aging: { d0_7: 45000, d8_30: 68000, d31_60: 32000 },
      intercompany: { counterparty: "f5", balance: 22000, direction: "owed_to_ss" },
      mgmt_accounts_last: "never",
    },
    {
      id: "f5", name: "Fortune 5 Distribution LLC", short: "Fortune 5",
      type: "operating", jurisdiction: "OMN", currency: "OMR", ownership: 100, status: "active", color: "#C4935A",
      description: "Oman. Perfume distribution. Intercompany balances with Six Scents unreconciled.",
      tax_rate: 15, tax_regime: "Oman CT",
      cash: 42000, debt: 0, receivables: 68000, payables: 31000, monthly_burn: 28000,
      receivables_aging: { d0_30: 38000, d31_60: 21000, d61_90: 9000, d90p: 0 },
      payables_aging: { d0_7: 12000, d8_30: 19000, d31_60: 0 },
      intercompany: { counterparty: "ss", balance: 22000, direction: "owed_by_f5" },
      mgmt_accounts_last: "never",
    },
    {
      id: "ab", name: "A Beauty Inc Limited", short: "A Beauty",
      type: "venture", jurisdiction: "GBR", currency: "GBP", ownership: 20, status: "blocked", color: "#C45A5A",
      description: "Company 15824605. 20% Kunal / 80% Arman Gosha. Beauty Bay APA buyer entity. BLOCKED: fatal deed defect, SHA absent, HoldCo not incorporated.",
      tax_rate: 25, tax_regime: "UK CT",
      cash: 0, debt: 0, receivables: 0, payables: 0, monthly_burn: 0,
      receivables_aging: { d0_30: 0, d31_60: 0, d61_90: 0, d90p: 0 },
      payables_aging: { d0_7: 0, d8_30: 0, d31_60: 0 },
      intercompany: null,
      mgmt_accounts_last: "n/a",
    },
    {
      id: "hc", name: "Kunal HoldCo Ltd", short: "HoldCo",
      type: "holdco", jurisdiction: "GBR", currency: "GBP", ownership: 100, status: "not_incorporated", color: "#9A5AC4",
      description: "NOT YET INCORPORATED. Required before Beauty Bay completion. DIFC free zone vehicle recommended to preserve UAE residency and avoid UK SRT exposure.",
      tax_rate: 25, tax_regime: "UK CT (planned)",
      cash: 0, debt: 0, receivables: 0, payables: 0, monthly_burn: 0,
      receivables_aging: { d0_30: 0, d31_60: 0, d61_90: 0, d90p: 0 },
      payables_aging: { d0_7: 0, d8_30: 0, d31_60: 0 },
      intercompany: null,
      mgmt_accounts_last: "n/a",
    },
    {
      id: "kw", name: "Kayfa / Kritixs / Wazn", short: "KKW Brands",
      type: "venture", jurisdiction: "UAE", currency: "AED", ownership: 100, status: "development", color: "#5A7EC4",
      description: "3 proprietary brands. Kayfa (luxury/French-Arabic), Kritixs (prestige/urban), Wazn (sporty/mass). Zero trademark filings globally. Zero revenue.",
      tax_rate: 9, tax_regime: "UAE CT",
      cash: 0, debt: 0, receivables: 0, payables: 0, monthly_burn: 8000,
      receivables_aging: { d0_30: 0, d31_60: 0, d61_90: 0, d90p: 0 },
      payables_aging: { d0_7: 0, d8_30: 0, d31_60: 0 },
      intercompany: null,
      mgmt_accounts_last: "n/a",
    },
    {
      id: "px", name: "Personal (KM)", short: "Personal",
      type: "personal", jurisdiction: "UAE", currency: "AED", ownership: 100, status: "active", color: "#5AB88A",
      description: "Palm Jumeirah property. Personal obligations and lifestyle burn.",
      tax_rate: 0, tax_regime: "UAE (no personal income tax)",
      cash: 220000, debt: 0, receivables: 0, payables: 0, monthly_burn: 55000,
      receivables_aging: { d0_30: 0, d31_60: 0, d61_90: 0, d90p: 0 },
      payables_aging: { d0_7: 0, d8_30: 0, d31_60: 0 },
      intercompany: null,
      mgmt_accounts_last: "n/a",
    },
  ],
  accounts: [
    { id: "ss_ae", entity: "ss", bank: "Emirates NBD", currency: "AED", balance: 310000, type: "current", flag: null },
    { id: "ss_eu", entity: "ss", bank: "Emirates NBD", currency: "EUR", balance: 480000, type: "current", flag: "FX_MONITOR" },
    { id: "ss_us", entity: "ss", bank: "RAKBANK", currency: "USD", balance: 47000, type: "current", flag: null },
    { id: "f5_or", entity: "f5", bank: "Bank Muscat", currency: "OMR", balance: 42000, type: "current", flag: null },
    { id: "px_ae", entity: "px", bank: "Emirates NBD", currency: "AED", balance: 220000, type: "personal", flag: null },
  ],
  ventures: [
    {
      id: "v_ab", entity: "ab", name: "Beauty Bay — A Beauty Inc",
      thesis: "Acquire distressed UK beauty e-commerce brand via APA. 20% minority. Leverage existing fragrance distribution competencies.",
      capital_committed: 1750000, capital_paid: 0, currency: "GBP",
      apa_purchase_price: 300000,
      unexplained_gap: 1450000,
      ownership_pct: 20, co_investor: "Arman Gosha (80%)",
      moic_bear: 0, moic_base: 3.5, moic_bull: 6,
      status: "blocked",
      sha_status: "absent",
      holdco_status: "not_incorporated",
      deed_status: "fatal_defect",
      key_blockers: [
        "APA deed: one admin signed, not two. IA 1986 Sch B1 para 100(2). Deed may be void.",
        "Cl 20.7: no remedy if Seller has no title. Cl 1.3: zero title warranties.",
        "SHA absent — no anti-dilution, veto, tag-along, information rights.",
        "HoldCo not incorporated — no clean UK holding vehicle.",
        "\u00A31.45M gap: \u00A31.75M investment vs \u00A3300k APA price. Unexplained in writing.",
        "Cl 8.1: Beauty Bay name ownership unconfirmed. \u00A3911k GXO stock BFBB-branded.",
      ],
      funding_milestones: [
        { label: "HoldCo incorporated", due: rel(6), status: "open" },
        { label: "SHA agreed", due: rel(4), status: "open" },
        { label: "Deed defect corrected", due: rel(10), status: "open" },
        { label: "\u00A31.45M gap explained in writing", due: rel(7), status: "open" },
        { label: "APA completion", due: rel(21), status: "blocked" },
      ],
      kill_criteria: `If HoldCo not incorporated by ${rel(14)} OR SHA not agreed by ${rel(10)} OR deed defect not corrected \u2014 recommend walking. MOIC bear case = 0.`,
      next_decision_date: rel(7),
    },
    {
      id: "v_kw", entity: "kw", name: "KKW Brand Portfolio",
      thesis: "Build proprietary fragrance brand equity across 3 segments. UAE-first, then international.",
      capital_committed: 250000, capital_paid: 48000, currency: "AED",
      apa_purchase_price: null, unexplained_gap: null,
      ownership_pct: 100, co_investor: "None",
      moic_bear: 0, moic_base: null, moic_bull: null,
      status: "development",
      sha_status: "n/a", holdco_status: "n/a", deed_status: "n/a",
      key_blockers: [
        "Zero trademark filings globally. IP can be squatted.",
        "No revenue model or launch timeline confirmed.",
        "3 brands simultaneously = resource dilution.",
      ],
      funding_milestones: [
        { label: "UAE trademark filings \u2014 all 3 brands", due: rel(14), status: "open" },
        { label: "WIPO Madrid filing", due: rel(30), status: "open" },
        { label: "Revenue model confirmed", due: rel(60), status: "open" },
      ],
      kill_criteria: `If trademark filings not initiated by ${rel(21)} AND no revenue model by ${rel(90)} \u2014 reassess full capital allocation. Sunk cost so far: AED 48k.`,
      next_decision_date: rel(21),
    },
    {
      id: "v_bp", entity: "px", name: "Baccarose / Parcos (India)",
      thesis: "Acquire Indian multi-brand beauty retail. Leverage existing brand relationships in fragrance.",
      capital_committed: 0, capital_paid: 0, currency: "USD",
      apa_purchase_price: null, unexplained_gap: null,
      ownership_pct: null, co_investor: "TBD",
      moic_bear: null, moic_base: null, moic_bull: null,
      status: "evaluation",
      sha_status: "n/a", holdco_status: "n/a", deed_status: "n/a",
      key_blockers: [
        "FEMA/FDI compliance path not confirmed.",
        "100% FDI single-brand retail complex operationally.",
        "No clear competitive advantage defined.",
        "Management bandwidth: Beauty Bay not closed yet.",
      ],
      funding_milestones: [],
      kill_criteria: "If FEMA structure not confirmed within 60 days AND no operational thesis \u2014 kill. No capital committed.",
      next_decision_date: rel(45),
    },
  ],
  obligations: [
    { id: "o1", entity: "ab", class: "legal_blocker", priority: "CRITICAL", owner: "Kunal + solicitor",
      description: "APA \u2014 halt all funds transfer. Deed void (one admin signed). SHA absent. Both must be resolved before any capital moves.",
      amount: 1750000, currency: "GBP", due: rel(10), status: "blocked",
      blocking: "Deed defect + SHA absent", evidence_link: "" },
    { id: "o2", entity: "hc", class: "legal_blocker", priority: "CRITICAL", owner: "UK solicitor",
      description: "Incorporate Kunal HoldCo Ltd. DIFC free zone vehicle recommended. Hard prerequisite for APA completion.",
      amount: 3500, currency: "GBP", due: rel(6), status: "open",
      blocking: "None \u2014 instruct solicitor today", evidence_link: "" },
    { id: "o3", entity: "ab", class: "legal_blocker", priority: "CRITICAL", owner: "Corporate lawyer",
      description: "SHA \u2014 A Beauty Inc Limited. Must include: anti-dilution, pre-emption, veto, tag-along, information rights, reserved matters, conflict of interest policy.",
      amount: 15000, currency: "GBP", due: rel(4), status: "open",
      blocking: "None \u2014 instruct immediately", evidence_link: "" },
    { id: "o4", entity: "kw", class: "legal_blocker", priority: "HIGH", owner: "IP lawyer",
      description: "Trademark filings: Kayfa, Kritixs, Wazn. UAE Ministry of Economy + WIPO Madrid Protocol + UKIPO.",
      amount: 18000, currency: "USD", due: rel(14), status: "open",
      blocking: "None", evidence_link: "" },
    { id: "o5", entity: "ss", class: "treasury", priority: "HIGH", owner: "Kunal",
      description: "EUR \u20AC480k conversion decision. Define rate threshold and execute. Holding = active undocumented currency position.",
      amount: 480000, currency: "EUR", due: null, status: "open",
      blocking: "No rate trigger defined", evidence_link: "" },
    { id: "o6", entity: "f5", class: "payment", priority: "MEDIUM", owner: "F5 Finance",
      description: "Fortune 5 Q1 supplier settlement \u2014 Bank Muscat OMR.",
      amount: 31000, currency: "OMR", due: rel(5), status: "open",
      blocking: "None", evidence_link: "" },
    { id: "o7", entity: "ss", class: "control_action", priority: "MEDIUM", owner: "Controller",
      description: "Six Scents: AED 27k overdue 90d+. Produce aging report. Escalate to collections or write-off decision.",
      amount: 27000, currency: "AED", due: rel(3), status: "open",
      blocking: "No aging report produced", evidence_link: "" },
    { id: "o8", entity: "ss", class: "control_action", priority: "MEDIUM", owner: "Controller",
      description: "Reconcile Six Scents \u2194 Fortune 5 intercompany balances (AED 22k). No reconciliation on record.",
      amount: 22000, currency: "AED", due: rel(7), status: "open",
      blocking: "No intercompany reconciliation", evidence_link: "" },
    { id: "o9", entity: "kw", class: "payment", priority: "LOW", owner: "Kunal",
      description: "KKW brand dev: decide commit/kill on Kayfa city collection packaging spend.",
      amount: 8000, currency: "AED", due: rel(21), status: "open",
      blocking: "None", evidence_link: "" },
  ],
  decisions: [
    {
      id: "d1", date: "2026-02-14", entity: "ab",
      title: "Proceed with Beauty Bay APA due diligence",
      amount: 1750000, currency: "GBP", decision_type: "investment",
      rationale: "Distressed brand with e-commerce infrastructure. 20% minority alongside Arman's operational lead. Thesis: rebuild brand equity.",
      assumptions: ["Beauty Bay name owned free and clear by Seller", "\u00A3150k GXO stock realizable", "Premises secure post-completion", "TOGC VAT treatment accepted by HMRC", "Arman's \u00A31.4M is genuine equity"],
      downside: "Total loss if deed void or title fails. Unlimited VAT exposure (Cl 6.3). GDPR breach risk. Kunal personally exposed absent SHA.",
      review_date: rel(7), status: "under_review", outcome: "",
    },
  ],
  issues: [
    { id: "i1", severity: "CRITICAL", label: "Void Deed", entity: "ab",
      description: "Only one of two joint administrators signed the APA. IA 1986 Sch B1 para 100(2): both must sign jointly. Deed may be void ab initio.",
      action: "Require both admins to sign. Obtain insolvency QC opinion before any funds move." },
    { id: "i2", severity: "CRITICAL", label: "No Title + No Remedy", entity: "ab",
      description: "Cl 1.3: zero title warranties. Cl 20.7: no remedy if Seller has no title. Combined: pay \u00A31.75M, receive unenforceable assets.",
      action: "Delete Cl 20.7. Demand title certificates as completion condition precedent." },
    { id: "i3", severity: "CRITICAL", label: "\u00A31.45M Gap", entity: "ab",
      description: "APA purchase price = \u00A3300k. Kunal investing \u00A31.75M. \u00A31.45M has no contractual basis. Must be explained in writing from Arman before any funds transfer.",
      action: "Demand written explanation. No funds transfer until gap is documented." },
    { id: "i4", severity: "CRITICAL", label: "SHA Absent", entity: "ab",
      description: "No SHA. No veto, anti-dilution, tag-along, information rights, conflict of interest policy re Arman.",
      action: "Instruct corporate lawyer today. SHA must precede any funds transfer." },
    { id: "i5", severity: "CRITICAL", label: "HoldCo Not Incorporated", entity: "hc",
      description: "Kunal has no UK holding vehicle. Cannot complete Beauty Bay as a clean minority position without it.",
      action: "Instruct UK solicitor immediately. DIFC free zone structure recommended." },
    { id: "i6", severity: "HIGH", label: "EUR \u20AC480k Unresolved", entity: "ss",
      description: "Large EUR position with no defined conversion trigger. Holding = undocumented currency bet. AED equivalent \u2248 AED 1.89M.",
      action: "Define rate threshold. Execute or formally document hold thesis." },
    { id: "i7", severity: "HIGH", label: "Zero IP Filings \u2014 KKW", entity: "kw",
      description: "3 brands, zero trademark filings globally. IP can be squatted today at zero cost to a third party.",
      action: "File UAE + WIPO Madrid + UKIPO this week. Est. USD 18k." },
    { id: "i8", severity: "HIGH", label: "AED 27k Receivables 90d+", entity: "ss",
      description: "Six Scents has AED 27k overdue 90+ days. No aging report. No chase underway. Default risk increasing.",
      action: "Produce aging report. Escalate 90d+ to legal or write-off decision." },
    { id: "i9", severity: "MEDIUM", label: "Intercompany Unreconciled", entity: "ss",
      description: "Six Scents / Fortune 5 intercompany balance AED 22k unreconciled. No documentation.",
      action: "Reconcile within 7 days. Document the transfer basis." },
    { id: "i10", severity: "MEDIUM", label: "No Management Accounts", entity: "ss",
      description: "Six Scents and Fortune 5 have never produced management accounts. Financial visibility is zero.",
      action: "Establish monthly management account process. Starting this month." },
  ],
  config: {
    min_entity_cash: { ss: 150000, f5: 20000, ab: 0, hc: 0, kw: 0, px: 100000 },
    beauty_bay_commitment_gbp: 1750000,
    eur_position: 480000,
  },
};

export default STATE;
